image: node:12.20.1
definitions:
  caches:
    git-modules: .git/modules
  scripts:
    - script: &script-test
        - npm install
        - npm install typescript@3.1.6 --save-dev
        - npm run test
        - npm run lint
    - script: &script-build-dev
        - npm install
        - npm install typescript@3.1.6 --save-dev
        - npm run build
    - script: &script-build-prod
        - npm install
        - npm install typescript@3.1.6 --save-dev
        - npm run version
        - npm run buildProd
    - script: &script-firebase-deploy
        - npm install firebase-tools@8.6.0
        - pipe: atlassian/firebase-deploy:0.3.0
          variables:
             FIREBASE_TOKEN: "1//0gG0fqbeoHCKBCgYIARAAGBASNwF-L9IrlMiUiRc_qs3LNHc7HbkINwK1Ben0na-Ei5QFh-zosxDoenE3-aY8txY-7fwmFSVsm8k"

    - script: &script-deploy-preview
        - npm install -g firebase-tools@8.12
        - BITBUCKET_BRANCH=${BITBUCKET_BRANCH:=preview}
        - firebase hosting:channel:deploy ${BITBUCKET_BRANCH#"feature/"} --token $FIREBASE_TOKEN --only $FIREBASE_HOSTING
  
  steps:
    - step: &step-test
        name: Test
        caches:
          - node
        script: *script-test
    - step: &step-build-prod
        name: Build Prod
        caches:
          - node
        script: *script-build-prod
    - step: &step-build-dev
        name: Build Dev
        script: *script-build-dev
    - step: &step-deploy-test
        name: Deploy to Test
        deployment: Test
        caches:
          - node
        script: *script-firebase-deploy
   
pipelines:
  custom:
    deploy-to-staging: &pipeline-staging
      - step: *step-build-dev
      - step: *step-deploy-test
    deploy-to-production: &pipeline-prod
      - step: *step-build-prod
      - step: *step-deploy-test
  pull-requests:
    bugfix/**: *pipeline-staging
    feature/**: *pipeline-staging
  branches:
    master: *pipeline-prod
    hotfix/**: *pipeline-staging
    release/**: *pipeline-staging
    stable: *pipeline-prod